### ISSUE TITLE
Documentação de Contexto : Problema

### ISSUE THREAD

**Issue by StephanieGadoniS** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t1-projeto-moradores-de-rua#2]

**Comment by AnthonyLuanSS** [comment]
@AnthonyLuanSS  
Conforme definição da Secretaria Nacional de Assistência Social, a população em situação de rua se caracteriza por ser um grupo populacional heterogêneo, composto por pessoas com diferentes realidades, mas que têm em comum a condição de pobreza absoluta, vínculos interrompidos ou fragilizados e falta de habitação convencional regular, sendo compelidas a utilizar a rua como espaço de moradia e sustento, por caráter temporário ou de forma permanente.
