### ISSUE TITLE
Documentação de Contexto : Objetivos

### ISSUE THREAD

**Issue by StephanieGadoniS** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t1-projeto-moradores-de-rua#3]

**Comment by ViniciusSOTech** [comment]
Desenvolver um software que ajude lidar melhor com um problema muito comum do nosso cotidiano e que é principalmente encontrado em cidades maiores que são os moradores em situação de rua. 
Focar em adquirir informações relevantes sobre ogns em Belo Horizonte que auxiliam essas pessoas encontradas nesse tipo de situação e trabalhar para que essa informação chegue de forma eficiente aos nossos futuros usuários.

**Comment by ViniciusSOTech** [comment]
Desenvolver um software que ajude lidar melhor com um problema muito comum do nosso cotidiano e que é principalmente encontrado em cidades maiores que são os moradores em situação de rua. 
Focar em adquirir informações relevantes sobre ONGs em Belo Horizonte que auxiliam essas pessoas encontradas nesse tipo de situação e trabalhar para que essa informação chegue de forma eficiente aos nossos futuros usuários.
